name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libclang-dev
      - name: Cargo build
        run: cargo build --verbose
      - name: Cargo test
        run: cargo test --verbose

  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Nix build
        run: |
          nix flake check
          nix build --verbose --print-build-logs --cores 0 --max-jobs auto
